### ISSUE TITLE
Headless Server fails to start after updating FTB Chunks: NoClassDefError

### ISSUE THREAD

**Issue by belathus** [FTBTeam/FTB-Teams#10]
https://gist.github.com/belathus/a3ff691d860f8543a0e1a772cafca1b3

Though, I guess this is more an FTB Chunks issue?

**Comment by MichaelHillcox** [comment]
Please update the FTB mods in your pack, looks like it's just a bit out of date :+1:

Closing for now, please comment if this doesn't fix your issue.
