### ISSUE TITLE
Allow players to be in multiple teams

### ISSUE THREAD

**Issue by PssbleTrngle** [FTBTeam/FTB-Teams#11]
I know this would probably be a code-breaking feature requiring lots of work but it would be great nonetheless

**Comment by LatvianModder** [comment]
Not happening. Players can be allies in other teams, but to be member of multiple would mean complete nightmare for chunk permissions and FTB Quests progression and other things. If you had ability to be in multiple but switch between your "main", then that would open doors to cheating with quests rewards most likely
