### ISSUE TITLE
FTB Teams (ftbteams) has failed to load correctly

### ISSUE THREAD

**Issue by EliteXtrem** [FTBTeam/FTB-Teams#14]
*user did not pastebin the crash so I did*
https://paste.feed-the-beast.com/view/aa7fb76f

**Comment by MichaelHillcox** [comment]
Please try and use the latest version of FTB Library

**Comment by MichaelHillcox** [comment]
Closing for now, please comment if this doesn't fix your issue.

**Comment by EliteXtrem** [comment]
i have but dont work

**Comment by MichaelHillcox** [comment]
And you tell me what version of FTB Lib and FTB teams you have?

**Comment by EliteXtrem** [comment]
ftb-teams-forge-1605.2.1-build.8
ftb-gui-library-1605.2.1.41-forge

**Comment by jasperfirecai2** [comment]
since the build from 3 days ago, FTB teams tries to load ftb-library (which is in alpha) yet the latest recommended ftb chunks requires the latest stable ftb-gui-library. they are not cross compatible
