### ISSUE TITLE
[bug] Teams(?) is crashing my game when I claim chunks

### ISSUE THREAD

**Issue by AKSchmitty** [FTBTeam/FTB-Teams#15]
I'm using version ftb-teams-forge-1605.2.1-build.12.jar and my forge version is forge-1.16.5-36.1.32
Here's my crash log
https://pastebin.com/Crg2v7Wx

**Comment by MaxNeedsSnacks** [comment]
You're using an outdated version of FTB Teams with a new version FTB Chunks. Please try updating everything to the latest versions on CurseForge (currently marked as betas) and reopen this issue if you can still reproduce this ^^

**Comment by AKSchmitty** [comment]
Still having the same issue with everything auto updated ( https://pastebin.com/dkvwh7Ve ) and using the beta builds of both FTB Teams and Chunks ( https://pastebin.com/MfW7LhNn )
Using both beta builds the world would generate but I would be kicked the moment I joined and auto updating gave me the beta build of Teams and the latest release of Chunks. I couldn't find a version of Teams to match the versions of Chunks listed on Curseforge

**Comment by MaxNeedsSnacks** [comment]
You still have an old version of FTB Ranks, so now *that's* failing unfortunately

**Comment by AKSchmitty** [comment]
That worked, thank you so much
