### ISSUE TITLE
[bug] Server crash on 2 or more people entering the server

### ISSUE THREAD

**Issue by GAMMACASE** [FTBTeam/FTB-Teams#16]
**Mod version**
ftb-teams-forge-1605.2.1-build.12

**Forge version**
forge-1.16.5-36.1.16

**Crash report**
https://pastebin.com/dgJXEi4x

**How to reproduce the issue**
Server crashes upon 2 or more people entering the server.

**Comment by MaxNeedsSnacks** [comment]
You're using an old version of Chunks with a new version of Teams.

Generally, if you're updating to the alphas, you should probably try and update all mods, since otherwise you may have some that depend on older versions ^^

**Comment by GAMMACASE** [comment]
Oh, I see, thanks for the reply.
