### ISSUE TITLE
[bug] Fake Players Support

### ISSUE THREAD

**Issue by Joly0** [FTBTeam/FTB-Teams#17]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.
In the current alpha realase of the mod, there is no support for fake players.
As far as i know, one could add a fake player through the allies window from the claimed chunks page? (i cant remember exactly) and from there on the fake players would work in claimed chunks.

Currently i cant see such an option and the FTB Teams button on the top left of my inventory just opens a window saying "This UI is WIP! Use /ftbteams for now!" which is fine, but using the commands there is no command to add fake players either. I cant open the settings from the ui i just said and enable block edit mode, interact mode or free to join aswell as allow fake players and set everything to true or public, but nothing happens.

This problems occurs for me using the industrial foregoing block breakers, i cant tell right know, if this happens with other fake players aswell

**Mod & Pack version**
ftb-teams-forge-1605.2.1-build.12.jar
**Forge / Fabric version, if applicable**
Forge 36.1.16
**Modpack (with version), if applicable**
Seaopolis Version 1.5
**If the issue is a crash; An external link to the crash report**
No crash
**How to reproduce the issue**
*Please provide use with a step by step description*

**A screenshot, if applicable**

**Anything else we should know?**

**Comment by MaxNeedsSnacks** [comment]
You can still add allies using commands:

`/ftbteams party allies add [...players]`

The GUI is very much work in progress unfortunately still, so this'll be your best bet for now

**Comment by DizzyDJW** [comment]
> ~You can still add allies using commands: `/ftbteams party allies add [...players]` The GUI is very much work in progress unfortunately still, so this'll be your best bet for now~
> 
> Got an update on this from Lat, fake players SHOULD be allied by default, so they should be able to place and break blocks as well

"Should"
They don't... I have a builder set up and changing the options for Block Edit Mode and Block Interact Mode, to literally anything, makes no difference. Fake Players still can't break blocks in my claimed chunks.
