### ISSUE TITLE
`Team not found!` error

### ISSUE THREAD

**Issue by zderApfel** [FTBTeam/FTB-Teams#18]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
FTBTeams Forge 1605.2.1-build.17

**Forge / Fabric version, if applicable**
Forge-1.16.5-36.1.32

**Modpack (with version), if applicable**
N/A

**If the issue is a crash; An external link to the crash report**
N/A

**How to reproduce the issue**
These are the mods installed server-side:
![image](https://user-images.githubusercontent.com/67031028/124368044-e265ed80-dc2a-11eb-9a6f-a9a137d9dc5e.png)
![image](https://user-images.githubusercontent.com/67031028/124368047-eb56bf00-dc2a-11eb-8e17-9d87bb1eeb3a.png)
*Please provide use with a step by step description*

When I try to change a team's settings with the `/ftbteams server settings ...`, I get the message `Team <team name> not found!`

Command used here is: `/ftbteams server settings Portsmouth#4b1b20fd ftbteams:description Insert description`
![image](https://user-images.githubusercontent.com/67031028/124368070-22c56b80-dc2b-11eb-897a-9728ce7cb1fe.png)

**Comment by MaxNeedsSnacks** [comment]
That command is specifically for "server teams" (which can be used for spawn protection, admin areas, etc.)

Try using `/ftbteams party settings Portsmouth#4b1b20fd ftbteams:description Insert description` instead

**Comment by zderApfel** [comment]
> That command is specifically for "server teams" (which can be used for spawn protection, admin areas, etc.)
> 
> Try using `/ftbteams party settings Portsmouth#4b1b20fd ftbteams:description Insert description` instead

Okay. So how would I go about changing team settings? The UI is still buggy and doesn't load most of the time

**Comment by zderApfel** [comment]
It says that's not a valid command

**Comment by MaxNeedsSnacks** [comment]
Right, might be a missing command then. I'll pass this on to Lat ^^

**Comment by zderApfel** [comment]
> Right, might be a missing command then. I'll pass this on to Lat ^^

Thank you!

**Comment by zderApfel** [comment]
How do you enable mob griefing in claimed chunks?
