### ISSUE TITLE
[1.16.4] FTB Quests completion not syncing within a team

### ISSUE THREAD

**Issue by RaalphL** [FTBTeam/FTB-Teams#2]
I was playing on a private server with my friends, and when we joined a team and completed quests, it wouldn't complete for the other people who didn't. This happened with all quest types, not only the checkbox ones.

**Comment by MokahTGS** [comment]
Yes, I've reported this in the Quests issues but it is actually a Teams issue.

https://github.com/FTBTeam/FTB-Quests/issues/470

**Comment by Cosmicblast2** [comment]
Yeah I would like to bump this issue higher personally. Started playing Sky Bees with my daughter and the quests not syncing make it a bit annoying.

**Comment by MokahTGS** [comment]
I'd like this added as a priority as well.

**Comment by MichaelHillcox** [comment]
This isn't an issue with Teams specifically, the issue lays with how the quest mod was handling the intergration. This has also been fixed is quests to my knowledge :+1:
