### ISSUE TITLE
[1.16.4] Missing Teams GUI

### ISSUE THREAD

**Issue by sanchits2003** [FTBTeam/FTB-Teams#4]
FtbTeams 1.16.4 is missing the teams gui button, making using commands (/ftbteams *) the only way to manage teams.
![image](https://user-images.githubusercontent.com/38894210/104534042-a1bbed00-5667-11eb-9e1b-565d74d501fc.png)

**Comment by MichaelHillcox** [comment]
This has been added back now :+1: update your version
