### ISSUE TITLE
Missing Teams GUI [1.16.5]

### ISSUE THREAD

**Issue by storiofmylife** [FTBTeam/FTB-Teams#6]
None of the Teams icons are appearing for me. My GUI Library, Teams, and Architectury are all up to date. I've even tried without using OptiFine and OptiForge. The FTB Quests icon shows up fine.

**Comment by MaxNeedsSnacks** [comment]
Teams doesn't have a GUI yet unfortunately, as said in #4, the command is ***currently*** the only way to manage them, but that should hopefully change soon

**Comment by storiofmylife** [comment]
Thanks for letting me know!
